architectures:
  task:
    languages:
      go:
        baseUrl: "https://github.com/Layr-Labs/hourglass-avs-template"
        version: "v0.0.12"
      ts:
        baseUrl: ""
        version: ""
      rust:
        baseUrl: ""
        version: ""
