services:
  devkit-devnet:
    image: ${FOUNDRY_IMAGE}
    volumes:
      - "${STATE_PATH}:/anvil/state.json"
    entrypoint: anvil
    command: "--host 0.0.0.0 --load-state /anvil/state.json ${ANVIL_ARGS}"
    ports:
      - "${DEVNET_PORT}:8545"
