name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["**"]

jobs:
  Test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout devkit-cli
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Clone hourglass-monorepo privately
        env:
          HOURGLASS_TOKEN: ${{ secrets.HOURGLASS_TOKEN }}
        run: |
          git config --global url."https://${HOURGLASS_TOKEN}@github.com/".insteadOf "https://github.com/"
          git clone --depth=1 https://github.com/Layr-Labs/hourglass-monorepo.git temp_external/hourglass-monorepo
          go mod edit -replace=github.com/Layr-Labs/hourglass-monorepo=./temp_external/hourglass-monorepo
          go mod tidy

      - name: Build
        run: make build
